### ISSUE TITLE
RetroArch issues in v0.8

### ISSUE THREAD

**Issue by XQuader** [rg35xx-cfw/rg35xx-cfw.github.io#41]
- Can't enable `Threaded Video` - crashes in any core (returning to the ES game list), reverts to 'OFF' even if I manually update the `retroarchcustom.cfg`  
- Can't close content - crashes in any core (returning to the ES game list)

**Comment by acmeplus** [comment]
Fixed here, will be added to v0.9.

[retroarch_update_20230428.zip](https://github.com/rg35xx-cfw/rg35xx-cfw.github.io/files/11353744/retroarch_update_20230428.zip)

**Comment by XQuader** [comment]
Still can't save `Threaded Video`, reverts to `OFF` even if I manually update the `retroarchcustom.cfg` (I have no overrides yet)

**Comment by acmeplus** [comment]
Ok. Not being able to save the global settings is normal.  That’s the way batocera works. Will check about the core override.

**Comment by acmeplus** [comment]
If you want video threaded on globally or by core you can add a variable in batocera.conf like global.retroarch.video_threaded=true. Replace global with the core name for a core specific setting.

**Comment by MauricioSuporte** [comment]
I formatted the sd card and installed the batocera-rg35xx-36-20230420.img.gz image, set it to read the games from a secondary sd, and after restarting, the music was distorted and the performance on the snes dropped drastically.
Did I do something wrong?

**Comment by acmeplus** [comment]
> I formatted the sd card and installed the batocera-rg35xx-36-20230420.img.gz image, set it to read the games from a secondary sd, and after restarting, the music was distorted and the performance on the snes dropped drastically.
> Did I do something wrong?

you need to copy the batocera.conf from the release page to your second card system/batocera.conf.

**Comment by MauricioSuporte** [comment]
It worked, but I noticed that the performance dropped a little while playing against 3 from snes in versions 0.7 and 0.8, using the default core

**Comment by acmeplus** [comment]
> It worked, but I noticed that the performance dropped a little while playing against 3 from snes in versions 0.7 and 0.8, using the default core

Opened #45 to keep track of these issues.

Closing this issue since the main issue reported has been fixed in v0.8.1
